labels: ["idea", "community-feedback"]

body:
  - type: markdown
    attributes:
      value: |
        💡 **Share your idea for Scrum Monsters!**
        
        This is a community space for discussing new features, bosses, and improvements. 
        Community members can vote and comment on ideas they'd like to see.

  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: What would you like to see added to Scrum Monsters?
      placeholder: I think it would be awesome if...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of idea is this?
      options:
        - 🎮 New Game Mechanic
        - 👾 New Boss Character
        - 🎨 Visual/Audio Enhancement
        - 🔌 Integration (Jira, Slack, etc.)
        - 🏢 Team/Enterprise Feature
        - 📊 Analytics/Reporting
        - 🌐 Accessibility
        - 📱 Mobile Improvement
        - 🎯 Other

  - type: textarea
    id: why
    attributes:
      label: Why Would This Be Useful?
      description: How would this improve the Scrum Monsters experience?
      placeholder: This would help teams...

  - type: textarea
    id: mockup
    attributes:
      label: Visual Mockup or Example (Optional)
      description: Share any sketches, screenshots, or examples from other tools
      placeholder: Paste image URLs or descriptions here...
