name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Scrum Monsters
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below to help us fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser/Environment
      description: Which browser(s) are you using?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Mobile Chrome (Android)
        - Other
    validations:
      required: true

  - type: dropdown
    id: game-phase
    attributes:
      label: Game Phase
      description: When did this bug occur?
      options:
        - Landing Page
        - Lobby Creation
        - Joining Lobby
        - Avatar Selection
        - Battle Phase
        - Score Submission
        - Results/Victory Screen
        - Other
    validations:
      required: true

  - type: input
    id: lobby-code
    attributes:
      label: Lobby Code (if applicable)
      description: The 6-character lobby code where the bug occurred
      placeholder: ABC123

  - type: textarea
    id: console-logs
    attributes:
      label: Browser Console Logs
      description: |
        Open browser DevTools (F12), go to Console tab, copy any error messages.
        This helps us debug faster!
      render: shell
      placeholder: Paste console output here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, videos, etc.)
      placeholder: Any additional details...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included steps to reproduce the bug
          required: true
        - label: I agree to follow the project's Code of Conduct
          required: true
