blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/xavisavvy/scrum-monsters/discussions
    about: Ask questions and discuss ideas with the community
  - name: 💡 Feature Ideas
    url: https://github.com/xavisavvy/scrum-monsters/discussions/categories/ideas
    about: Share and vote on new feature ideas
  - name: 🔒 Security Vulnerability
    url: https://github.com/xavisavvy/scrum-monsters/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 💬 Join Discord Community
    url: https://discord.gg/d6vGXbzNZe
    about: Connect with other users and get quick help
