/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns server health status for load balancer and monitoring
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket health check
         * @description Returns WebSocket server status including connected clients and lobbies
         */
        get: operations["getWebSocketHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the currently authenticated user or null if not logged in
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register new user
         * @description Create a new user account with email and password
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with email/password
         * @description Authenticate user with email and password credentials
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout current user
         * @description End the current session and clear authentication cookies
         */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available auth providers
         * @description Returns which authentication providers are configured and available
         */
        get: operations["getAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Returns the authenticated user's profile settings
         */
        get: operations["getUserProfile"];
        /**
         * Update user profile
         * @description Update the authenticated user's profile settings
         */
        put: operations["updateUserProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user stats
         * @description Returns the authenticated user's game statistics
         */
        get: operations["getUserStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get estimation history
         * @description Returns the authenticated user's past estimation records
         */
        get: operations["getEstimationHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get connected OAuth accounts
         * @description Returns the authenticated user's linked OAuth provider accounts
         */
        get: operations["getUserAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/display-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update display name
         * @description Update the authenticated user's display name
         */
        put: operations["updateDisplayName"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @description Unique user identifier */
            id: number;
            /** @description Unique username */
            username: string;
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /** @description Display name shown in game */
            displayName: string;
            /**
             * Format: uri
             * @description URL to user's avatar image
             */
            avatarUrl?: string | null;
        };
        UserProfile: {
            /** @description User ID this profile belongs to */
            userId: number;
            /** @description Preferred avatar character */
            preferredAvatar?: string | null;
            preferredTeam?: components["schemas"]["TeamType"];
            /** @description Whether audio is enabled */
            audioEnabled?: boolean | null;
            /** @description Music volume (0-1) */
            musicVolume?: number | null;
            /** @description Sound effects volume (0-1) */
            sfxVolume?: number | null;
            /** @description Additional user settings */
            settings?: {
                [key: string]: unknown;
            } | null;
            /**
             * Format: date-time
             * @description Profile creation timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Profile last update timestamp
             */
            updatedAt: string;
        };
        UserStats: {
            /** @description User ID these stats belong to */
            userId: number;
            /** @description Total number of estimations made */
            totalEstimations?: number;
            /** @description Total game sessions participated in */
            totalSessions?: number;
            /** @description Average estimation accuracy score */
            averageScore?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        EstimationHistory: {
            /** @description Estimation record ID */
            id: number;
            /** @description User who made the estimation */
            userId: number;
            /** @description Game session ID */
            sessionId?: string | null;
            /** @description The estimate value */
            estimate?: string | null;
            /** @description Final agreed value */
            finalValue?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        OAuthAccount: {
            /** @description Account record ID */
            id: number;
            /**
             * @description OAuth provider name
             * @enum {string}
             */
            provider: "google" | "github";
            /**
             * Format: date-time
             * @description When account was linked
             */
            createdAt: string;
        };
        /**
         * @description Team assignment for estimation
         * @enum {string|null}
         */
        TeamType: "developers" | "qa" | "spectators" | null;
        Error: {
            /** @description Error message */
            error: string;
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
            /** Format: date-time */
            timestamp: string;
        };
        WebSocketHealthResponse: {
            /** @constant */
            status: "ok";
            websocket: {
                /** @description Number of connected WebSocket clients */
                connected: number;
                /** @description Number of active game lobbies */
                lobbies: number;
                /** @description Transport types used by connected clients */
                transports: string[];
            };
            /** Format: date-time */
            timestamp: string;
        };
        WebSocketHealthError: {
            /** @constant */
            status: "error";
            /** @description Error description */
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
        RegisterRequest: {
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /** @description Password (minimum 8 characters) */
            password: string;
            /** @description Optional username (defaults to email prefix) */
            username?: string;
            /** @description Optional display name (defaults to username) */
            displayName?: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description User's email address
             */
            email: string;
            /** @description User's password */
            password: string;
        };
        AuthProviders: {
            /** @description Whether Google OAuth is available */
            google: boolean;
            /** @description Whether GitHub OAuth is available */
            github: boolean;
            /** @description Whether email/password login is available */
            local: boolean;
        };
        UpdateProfileRequest: {
            /** @description Preferred avatar character */
            preferredAvatar?: string;
            preferredTeam?: components["schemas"]["TeamType"];
            /** @description Whether audio is enabled */
            audioEnabled?: boolean;
            /** @description Music volume (0-1) */
            musicVolume?: number;
            /** @description Sound effects volume (0-1) */
            sfxVolume?: number;
            /** @description Additional settings */
            settings?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Not authenticated"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Operation failed"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Bad request - validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Invalid request parameters"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "timestamp": "2026-02-03T12:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getWebSocketHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "websocket": {
                     *         "connected": 5,
                     *         "lobbies": 2,
                     *         "transports": [
                     *           "websocket",
                     *           "websocket"
                     *         ]
                     *       },
                     *       "timestamp": "2026-02-03T12:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["WebSocketHealthResponse"];
                };
            };
            /** @description WebSocket server not initialized */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "error",
                     *       "message": "WebSocket server not initialized",
                     *       "timestamp": "2026-02-03T12:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["WebSocketHealthError"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user (or null if not authenticated) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"] | null;
                    };
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "john@example.com",
                 *       "password": "securepassword123",
                 *       "username": "johndoe",
                 *       "displayName": "John Doe"
                 *     }
                 */
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "john@example.com",
                 *       "password": "securepassword123"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Invalid credentials"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true
                     *     }
                     */
                    "application/json": {
                        /** @constant */
                        success: true;
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available authentication providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "google": true,
                     *       "github": true,
                     *       "local": true
                     *     }
                     */
                    "application/json": components["schemas"]["AuthProviders"];
                };
            };
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile: components["schemas"]["UserProfile"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    updateUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "preferredAvatar": "warrior",
                 *       "preferredTeam": "developers",
                 *       "audioEnabled": true,
                 *       "musicVolume": 0.7,
                 *       "sfxVolume": 0.8
                 *     }
                 */
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        profile: components["schemas"]["UserProfile"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getUserStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        stats: components["schemas"]["UserStats"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getEstimationHistory: {
        parameters: {
            query?: {
                /** @description Maximum number of records to return (default 50, max 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estimation history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        history: components["schemas"]["EstimationHistory"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getUserAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connected OAuth accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accounts: components["schemas"]["OAuthAccount"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    updateDisplayName: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "displayName": "John Doe"
                 *     }
                 */
                "application/json": {
                    /** @description New display name (2-50 characters) */
                    displayName: string;
                };
            };
        };
        responses: {
            /** @description Display name updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            /** @description Invalid display name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Display name must be 2-50 characters"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "User not found"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
