global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'scrumquest'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'
    scrape_timeout: 10s
